name: pyAutoPickup
version: ${project.version}
main: org.me.pyke.pyautopickup.PyAutoPickup
api-version: '1.20'
author: 666pyke

commands:
  pyautopickup:
    description: "Manage pyAutoPickup."
    usage: "/pyautopickup [toggle|msgtoggle|reload]"

permissions:
  pyautopickup.reload:
    description: "Allows reloading the pyAutoPickup configuration."
    default: op
