name: pyAutoPickup
version: 1.0
main: org.me.pyke.pyautopickup.PyAutoPickup
api-version: 1.20
author: 666pyke

commands:
  pyautopickup:
    description: "Reloads the plugin configuration."
    permission: "pyautopickup.reload"